-- Ejecutar en una transacción DESPUÉS de la migración y finalizar con ROLLBACK.
-- Usa únicamente usuarios/rendiciones sintéticos y folios explícitos negativos.
do $$
declare admin_id uuid; usuario uuid:=gen_random_uuid(); otro uuid:=gen_random_uuid(); aprobador uuid:=gen_random_uuid();
  r1 uuid:=gen_random_uuid(); r2 uuid:=gen_random_uuid(); i1 uuid:=gen_random_uuid(); i2 uuid:=gen_random_uuid();
  fondo uuid:=gen_random_uuid(); previa uuid:=gen_random_uuid(); v jsonb; primero jsonb; segundo jsonb; total numeric; fallo boolean;
begin
  select id into admin_id from public.profiles where rol='admin' and activo limit 1;
  if admin_id is null then raise exception 'Se necesita un admin existente para preparar las identidades de prueba.'; end if;
  perform set_config('request.jwt.claim.sub',admin_id::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
  insert into auth.users(id,email) values(usuario,'auditoria-'||usuario||'@test.invalid'),(otro,'auditoria-'||otro||'@test.invalid'),(aprobador,'auditoria-'||aprobador||'@test.invalid');
  insert into public.profiles(id,nombre,rol,activo) values(usuario,'Prueba A','empleado',true),(otro,'Prueba B','empleado',true),(aprobador,'Prueba aprobador','aprobador',true);
  perform set_config('request.jwt.claim.sub',usuario::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',usuario,'role','authenticated')::text,true);
  insert into public.rendiciones(id,folio,empleado_id,empleado_nombre,empresa) values(r1,-990001,usuario,'Prueba A','Prueba'),(r2,-990002,usuario,'Prueba A','Prueba');
  insert into public.rendicion_items(id,rendicion_id,tipo_item,monto,rut_proveedor,tipo_documento,nro_documento,adjunto_url)
    values(i1,r1,'ConDocumento',100,'76.717.691-0','Factura Electrónica','00123',usuario||'/a.pdf'),(i2,r1,'ConDocumento',50,null,null,null,usuario||'/b.pdf');
  select monto_total into total from public.rendiciones where id=r1; assert total=150,'Total inicial';
  fallo:=false;
  begin update public.rendicion_items set rendicion_id=r2 where id=i1; exception when raise_exception then fallo:=true; end;
  assert fallo,'Bloquear traslado de ítem';
  fallo:=false;
  begin update public.rendicion_items set adjunto_url=otro||'/privado.pdf' where id=i1; exception when raise_exception then fallo:=true; end;
  assert fallo,'Bloquear ruta ajena';
  select jsonb_agg(d) into v from public.buscar_documento_duplicado('767176910','123','Factura Electronica') d;
  assert jsonb_array_length(v)=1,'Duplicado normalizado';
  select jsonb_agg(d) into v from public.buscar_documento_duplicado('767176910','123','Boleta de Honorario') d;
  assert v is null,'No confundir tipos';
  fallo:=false;
  begin perform public.finalizar_rendicion(r1); exception when raise_exception then fallo:=true; end;
  assert fallo,'Bloquear autoaprobación';
  perform set_config('request.jwt.claim.sub',aprobador::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',aprobador,'role','authenticated')::text,true);
  fallo:=false;
  begin perform public.finalizar_rendicion(r1); exception when raise_exception then fallo:=true; end;
  assert fallo,'No finalizar con pendientes';
  update public.rendicion_items set estado='Aprobado' where id=i1;
  update public.rendicion_items set estado='Rechazado',motivo_rechazo='Prueba' where id=i2;
  select monto_total into total from public.rendiciones where id=r1; assert total=100,'Rechazado disminuye el total inmediatamente';
  assert (select monto_rendido=150 and monto_aprobado=100 from public.rendiciones where id=r1),'Montos rendido y aprobado separados';
  assert (select count(*) from public.rendicion_items_historial where rendicion_id=r1 and campo='estado')=2,'Auditoría de estados';
  v:=public.finalizar_rendicion(r1);
  assert v->'rendicion'->>'estado'='Aprobado','Estado final';
  assert (v->'rendicion'->>'monto_total')::numeric=100,'Total final';
  assert (v->'rendicion'->>'monto_rendido')::numeric=150,'Conservar monto presentado';
  assert (v->'rendicion'->>'monto_aprobado')::numeric=100,'Conservar monto aprobado';
  assert jsonb_array_length(v->'items')=2,'Snapshot completo';
  fallo:=false;
  begin update public.rendicion_items set estado='Rechazado' where id=i1; exception when raise_exception then fallo:=true; end;
  assert fallo,'Estado inmutable al cerrar';
  fallo:=false;
  begin update public.rendicion_items set monto=200 where id=i1; exception when raise_exception then fallo:=true; end;
  assert fallo,'Monto inmutable al cerrar';
  update public.rendicion_items set cuenta_contable='2.01.07.01' where id=i1;
  assert exists(select 1 from public.rendicion_items_historial where item_id=i1 and campo='cuenta_contable'),'Auditoría cuenta contable';
  insert into public.solicitudes_fondos(id,folio,empleado_id,empleado_nombre,empresa,monto_solicitado,motivo) values(fondo,-990001,otro,'Prueba B','Prueba',100,'Prueba');
  fallo:=false;
  begin update public.rendiciones set tipo_rendicion='FondoPorRendir',solicitud_fondo_id=fondo where id=r2; exception when raise_exception then fallo:=true; end;
  assert fallo,'Fondo ajeno o pendiente inválido';
  assert not has_function_privilege('anon','public.buscar_documento_duplicado(text,text,text)','EXECUTE'),'Anon sin RPC duplicados';
  assert not has_table_privilege('authenticated','public.ocr_previos','INSERT'),'Cola no admite INSERT del cliente';
  assert not has_table_privilege('authenticated','public.rendicion_items_historial','INSERT'),'Historial no admite fabricación';
  assert not has_function_privilege('authenticated','public.reservar_trabajos_ocr(uuid,integer)','EXECUTE'),'Reserva solo servidor';
  perform set_config('request.jwt.claim.sub','',true);
  perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  insert into public.ocr_previos(id,usuario_id,storage_path) values(previa,usuario,usuario||'/previo.pdf');
  primero:=public.reservar_trabajos_ocr(usuario,1);
  segundo:=public.reservar_trabajos_ocr(usuario,1);
  assert jsonb_array_length(primero)=1,'Primer procesador reserva';
  assert jsonb_array_length(segundo)=0,'Segundo procesador no duplica';
  insert into public.system_events(tipo,usuario_id,solicitud_id) values('prueba',usuario,fondo);
  assert public.reservar_cupo_notificacion(usuario,'notificar_aprobador',fondo),'Primer cupo de solicitud';
  assert not public.reservar_cupo_notificacion(usuario,'notificar_aprobador',fondo),'Cupo evita duplicar correo';
  -- Desactivación mediante identidad admin, sin tocar usuarios reales.
  perform set_config('request.jwt.claim.sub',admin_id::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
  update public.profiles set activo=false where id=usuario;
  perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{"role":"service_role"}',true);
  update public.ocr_previos set ocr_lease_hasta=now()-interval '1 minute' where id=previa;
  assert jsonb_array_length(public.reservar_trabajos_ocr(usuario,1))=0,'Cuenta desactivada no consume OCR';
end;
$$;
