-- ============================================================
-- Migración: Solicitudes de fondos por rendir
-- Ejecutar en: Supabase Dashboard > SQL Editor > New query > Run
-- (proyecto RindeWellness, el de lectura/escritura -- no el de contabilidad)
-- ============================================================

-- Paso PREVIO a una rendición de tipo "FondoPorRendir": el empleado pide
-- que se le entregue un monto (la entrega la hace Finanzas fuera de la
-- app, ej. por transferencia); un aprobador/admin aprueba o rechaza la
-- solicitud igual que una rendición. Una vez aprobada, el empleado la
-- elige al crear la(s) rendición(es) donde justifica en qué gastó ese
-- fondo (ver rendiciones.solicitud_fondo_id más abajo).
create table if not exists public.solicitudes_fondos (
  id uuid primary key default gen_random_uuid(),
  -- Correlativo propio de las solicitudes (independiente del folio de
  -- rendiciones). En la app se muestra como "S-{folio}" para no
  -- confundirlo con el N° de una rendición.
  folio bigint generated by default as identity,
  created_at timestamptz not null default now(),
  empleado_id uuid not null references auth.users(id),
  empleado_nombre text not null,
  rut_empleado text,
  empresa text not null,
  centro_costo text,
  monto_solicitado numeric(12,2) not null,
  motivo text not null,
  fecha_necesaria date,
  estado text not null default 'Pendiente' check (estado in ('Pendiente','Aprobado','Rechazado')),
  aprobador_id uuid references auth.users(id),
  aprobador_nombre text,
  fecha_aprobacion timestamptz,
  motivo_rechazo text
);

alter table public.solicitudes_fondos enable row level security;

drop policy if exists "solicitudes_fondos_select" on public.solicitudes_fondos;
drop policy if exists "solicitudes_fondos_insert_own" on public.solicitudes_fondos;
drop policy if exists "solicitudes_fondos_update_approver" on public.solicitudes_fondos;

-- mismo criterio que rendiciones: el empleado ve/crea las suyas, aprobador/admin ve y actualiza todas
create policy "solicitudes_fondos_select" on public.solicitudes_fondos
  for select using (
    empleado_id = auth.uid() or public.is_admin_or_aprobador()
  );

create policy "solicitudes_fondos_insert_own" on public.solicitudes_fondos
  for insert with check (empleado_id = auth.uid());

create policy "solicitudes_fondos_update_approver" on public.solicitudes_fondos
  for update using (
    empleado_id = auth.uid() or public.is_admin_or_aprobador()
  );

create index if not exists idx_solicitudes_fondos_empleado on public.solicitudes_fondos(empleado_id);
create index if not exists idx_solicitudes_fondos_estado on public.solicitudes_fondos(estado);

-- Vincula una rendición tipo "FondoPorRendir" con la solicitud que le dio
-- origen, para poder calcular cuánto del fondo entregado ya se rindió y
-- cuánto queda disponible (ver calcularSplitFondo en app.js).
alter table public.rendiciones add column if not exists solicitud_fondo_id uuid references public.solicitudes_fondos(id);
create index if not exists idx_rendiciones_solicitud_fondo on public.rendiciones(solicitud_fondo_id);
