-- ============================================================
-- RindeWellness - esquema Supabase
-- Ejecutar en: Supabase Dashboard > SQL Editor > New query
-- ============================================================

-- Perfiles de usuario (uno por persona que usa la app)
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nombre text not null,
  rut text,
  rol text not null default 'empleado' check (rol in ('empleado','aprobador','admin')),
  empresa_default text,
  cargo text,
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists cargo text;

-- Cabecera de cada rendición
create table if not exists public.rendiciones (
  id uuid primary key default gen_random_uuid(),
  -- Número correlativo simple para identificar la rendición de un vistazo
  -- (folio N° 1, 2, 3...), aparte del uuid interno que usa la base.
  folio bigint generated by default as identity,
  created_at timestamptz not null default now(),
  empleado_id uuid not null references auth.users(id),
  empleado_nombre text not null,
  rut_empleado text,
  tipo_rendicion text not null default 'Reembolso' check (tipo_rendicion in ('Reembolso','FondoPorRendir')),
  -- Empresa (una de las ~10 SpA del grupo) a la que se contabiliza TODA la rendición.
  -- Se elige una sola vez, a nivel de cabecera (no por ítem): una persona puede
  -- hacer varias rendiciones, una por cada empresa distinta.
  empresa text,
  monto_total numeric(12,2) not null default 0,
  estado text not null default 'Pendiente' check (estado in ('Pendiente','Aprobado','Rechazado')),
  aprobador_id uuid references auth.users(id),
  aprobador_nombre text,
  fecha_aprobacion timestamptz,
  numero_comprobante_kame text,
  comentario text,
  -- Motivo que escribe el aprobador cuando rechaza la rendición. Se le
  -- muestra al empleado en la app y se le envía por correo.
  motivo_rechazo text
);

-- Líneas / ítems de cada rendición
create table if not exists public.rendicion_items (
  id uuid primary key default gen_random_uuid(),
  rendicion_id uuid not null references public.rendiciones(id) on delete cascade,
  tipo_item text not null check (tipo_item in ('ConDocumento','SinDocumento')),
  nombre_proveedor text,
  rut_proveedor text,
  -- Sin CHECK de valores acá a propósito: tuvimos un problema real de
  -- normalización Unicode (la tilde de "ó" puede guardarse en dos formas de
  -- bytes distintas que se ven idénticas mostradas en pantalla, y eso hacía
  -- fallar la restricción incluso con el valor "correcto"). Los valores
  -- válidos ya los controla el formulario (ver TIPOS_DOCUMENTO en app.js).
  tipo_documento text,
  nro_documento text,
  fecha_vencimiento date,
  cuenta_contable text,
  categoria text,
  -- Se copia acá el valor elegido en rendiciones.empresa (mismo valor para todos
  -- los ítems de una misma rendición), para simplificar reportes/exportación.
  -- Nullable porque queda seteado por la app luego de crear la fila; no se exige
  -- a nivel de constraint para no romper inserts en dos pasos.
  empresa text,
  monto numeric(12,2) not null,
  descripcion text,
  adjunto_url text,
  existe_en_contabilidad boolean,
  comprobante_contable_encontrado text
);

-- Migraciones idempotentes por si la tabla ya existía sin estas columnas:
alter table public.rendiciones add column if not exists empresa text;
alter table public.rendiciones add column if not exists folio bigint generated by default as identity;
alter table public.rendicion_items alter column empresa drop not null;
alter table public.rendicion_items add column if not exists nombre_proveedor text;
-- Centro de Costo / Unidad de Negocio: distinto de "empresa" (razón social).
-- Necesario porque en Kame cada gasto directo (4.01.03.*) exige indicar la
-- unidad de negocio, y no siempre coincide con el nombre de la empresa
-- (ej. Dmoov Corp SpA puede tener varios centros: Casa Matriz, Chicureo, etc).
alter table public.rendicion_items add column if not exists centro_costo text;
-- La app cambió los nombres de tipo de documento para que coincidan
-- exactamente con la tabla oficial de Kame (con tilde, "Boleta de
-- Honorario" en singular). La restricción CHECK original quedó con los
-- valores viejos, y además un problema de normalización Unicode con la
-- tilde hacía fallar hasta el valor "correcto" -- se sacó la restricción
-- del todo, ver comentario en la definición de la columna más arriba.
alter table public.rendicion_items drop constraint if exists rendicion_items_tipo_documento_check;
-- Motivo del rechazo, para avisarle al empleado por qué se rechazó su rendición.
alter table public.rendiciones add column if not exists motivo_rechazo text;

-- Aprobación por ítem: el aprobador puede aceptar o rechazar cada gasto por
-- separado (ej. una boleta ilegible) sin tener que rechazar toda la
-- rendición. Los ítems Rechazados quedan fuera del monto_total y del
-- comprobante Kame; la "Aprobación general" (ver aprobarRendicion/
-- finalizarAprobacionRendicion en app.js) recién se puede cerrar cuando
-- ningún ítem queda en Pendiente.
alter table public.rendicion_items add column if not exists estado text not null default 'Pendiente' check (estado in ('Pendiente','Aprobado','Rechazado'));
alter table public.rendicion_items add column if not exists motivo_rechazo text;
-- Backfill: las rendiciones que ya estaban Aprobadas/Rechazadas antes de
-- este cambio dejan sus ítems reflejando el mismo estado final (si no,
-- quedarían mostrando "Pendiente" para siempre sin poder cambiarlo).
update public.rendicion_items ri
set estado = r.estado
from public.rendiciones r
where r.id = ri.rendicion_id and r.estado in ('Aprobado', 'Rechazado') and ri.estado = 'Pendiente';

create index if not exists idx_rendicion_items_rendicion_id on public.rendicion_items(rendicion_id);
create index if not exists idx_rendiciones_empleado on public.rendiciones(empleado_id);
create index if not exists idx_rendiciones_estado on public.rendiciones(estado);

-- ============================================================
-- Storage: bucket para fotos de comprobantes
-- ============================================================
insert into storage.buckets (id, name, public)
values ('comprobantes', 'comprobantes', false)
on conflict (id) do nothing;

-- ============================================================
-- Funciones auxiliares (SECURITY DEFINER)
-- ============================================================
-- Necesarias para evitar recursión infinita: una policy de "profiles" que
-- hiciera "select ... from profiles" dentro de su propia condición generaba
-- el error 42P17 "infinite recursion detected in policy for relation profiles".
-- Al envolver la consulta en una función SECURITY DEFINER, esta corre con los
-- privilegios de quien la creó (bypasseando RLS internamente) y la policy que
-- la usa deja de auto-referenciarse.
create or replace function public.is_admin_or_aprobador()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.rol in ('aprobador','admin')
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.rol = 'admin'
  );
$$;

-- ============================================================
-- RLS
-- ============================================================
alter table public.profiles enable row level security;
alter table public.rendiciones enable row level security;
alter table public.rendicion_items enable row level security;

drop policy if exists "profiles_select_own_or_approver" on public.profiles;
drop policy if exists "profiles_upsert_own" on public.profiles;
drop policy if exists "profiles_update_own" on public.profiles;
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
drop policy if exists "rendiciones_select" on public.rendiciones;
drop policy if exists "rendiciones_insert_own" on public.rendiciones;
drop policy if exists "rendiciones_update_approver" on public.rendiciones;
drop policy if exists "items_select" on public.rendicion_items;
drop policy if exists "items_insert_own" on public.rendicion_items;
drop policy if exists "items_update_approver" on public.rendicion_items;
drop policy if exists "comprobantes_insert_own" on storage.objects;
drop policy if exists "comprobantes_select_own_or_approver" on storage.objects;

-- profiles: cada usuario ve y edita su propio perfil; aprobador/admin ven todos;
-- solo admin puede cambiar el rol de otra persona (panel "Usuarios").
create policy "profiles_select_own_or_approver" on public.profiles
  for select using (
    id = auth.uid() or public.is_admin_or_aprobador()
  );

create policy "profiles_upsert_own" on public.profiles
  for insert with check (id = auth.uid());

create policy "profiles_update_own_or_admin" on public.profiles
  for update using (id = auth.uid() or public.is_admin());

-- rendiciones: el empleado ve/crea las suyas; aprobador/admin ve y actualiza todas
create policy "rendiciones_select" on public.rendiciones
  for select using (
    empleado_id = auth.uid() or public.is_admin_or_aprobador()
  );

create policy "rendiciones_insert_own" on public.rendiciones
  for insert with check (empleado_id = auth.uid());

create policy "rendiciones_update_approver" on public.rendiciones
  for update using (
    empleado_id = auth.uid() or public.is_admin_or_aprobador()
  );

-- rendicion_items: heredan visibilidad de la rendición padre
create policy "items_select" on public.rendicion_items
  for select using (
    exists (
      select 1 from public.rendiciones r
      where r.id = rendicion_items.rendicion_id
      and (r.empleado_id = auth.uid() or public.is_admin_or_aprobador())
    )
  );

create policy "items_insert_own" on public.rendicion_items
  for insert with check (
    exists (
      select 1 from public.rendiciones r
      where r.id = rendicion_items.rendicion_id and r.empleado_id = auth.uid()
    )
  );

-- El aprobador/admin necesita poder actualizar los ítems al "Verificar en
-- contabilidad" desde la pantalla de detalle (existe_en_contabilidad, etc).
create policy "items_update_approver" on public.rendicion_items
  for update using (
    exists (
      select 1 from public.rendiciones r
      where r.id = rendicion_items.rendicion_id
      and (r.empleado_id = auth.uid() or public.is_admin_or_aprobador())
    )
  );

-- Storage policies: cada usuario sube/lee sus propios archivos (carpeta = su user id)
create policy "comprobantes_insert_own" on storage.objects
  for insert with check (
    bucket_id = 'comprobantes' and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "comprobantes_select_own_or_approver" on storage.objects
  for select using (
    bucket_id = 'comprobantes' and (
      (storage.foldername(name))[1] = auth.uid()::text or public.is_admin_or_aprobador()
    )
  );

-- ============================================================
-- Restricción de cuentas de gasto por usuario ("gasto directo")
-- ============================================================
-- El usuario maestro (admin) decide qué cuentas de la categoría 4.01.03.*
-- puede usar cada empleado al cargar un ítem "Gasto directo" (SinDocumento).
-- Si una persona NO tiene ninguna fila acá, no está restringida: ve todas
-- las cuentas. En cuanto tiene al menos una fila, el dropdown de la app
-- se limita a esas.
create table if not exists public.perfil_cuentas (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles(id) on delete cascade,
  cuenta_cod text not null,
  cuenta_nombre text not null,
  created_at timestamptz not null default now(),
  unique (profile_id, cuenta_cod)
);

alter table public.perfil_cuentas enable row level security;

drop policy if exists "perfil_cuentas_select" on public.perfil_cuentas;
drop policy if exists "perfil_cuentas_admin_insert" on public.perfil_cuentas;
drop policy if exists "perfil_cuentas_admin_delete" on public.perfil_cuentas;

-- cada usuario ve sus propias cuentas permitidas; aprobador/admin ven todas
create policy "perfil_cuentas_select" on public.perfil_cuentas
  for select using (profile_id = auth.uid() or public.is_admin_or_aprobador());

-- solo el usuario maestro (admin) puede otorgar/quitar cuentas a otra persona
create policy "perfil_cuentas_admin_insert" on public.perfil_cuentas
  for insert with check (public.is_admin());

create policy "perfil_cuentas_admin_delete" on public.perfil_cuentas
  for delete using (public.is_admin());

-- ============================================================
-- Historial de cambios en ítems (auditoría)
-- ============================================================
-- Cuando el empleado o quien aprueba edita un ítem ya cargado (típicamente
-- para corregir la cuenta contable / Centro de Costo, o el monto), queda
-- registrado acá quién cambió qué y desde qué valor a cuál.
create table if not exists public.rendicion_items_historial (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.rendicion_items(id) on delete cascade,
  rendicion_id uuid not null references public.rendiciones(id) on delete cascade,
  usuario_id uuid not null references auth.users(id),
  usuario_nombre text,
  campo text not null,
  valor_anterior text,
  valor_nuevo text,
  created_at timestamptz not null default now()
);

alter table public.rendicion_items_historial enable row level security;

drop policy if exists "historial_select" on public.rendicion_items_historial;
drop policy if exists "historial_insert" on public.rendicion_items_historial;

create policy "historial_select" on public.rendicion_items_historial
  for select using (
    exists (
      select 1 from public.rendiciones r
      where r.id = rendicion_items_historial.rendicion_id
      and (r.empleado_id = auth.uid() or public.is_admin_or_aprobador())
    )
  );

create policy "historial_insert" on public.rendicion_items_historial
  for insert with check (usuario_id = auth.uid());

-- ============================================================
-- Solicitudes de fondos por rendir
-- ============================================================
-- Paso PREVIO a una rendición de tipo "FondoPorRendir": el empleado pide
-- que se le entregue un monto (la entrega la hace Finanzas fuera de la
-- app, ej. por transferencia); un aprobador/admin aprueba o rechaza la
-- solicitud igual que una rendición. Una vez aprobada, el empleado la
-- elige al crear la(s) rendición(es) donde justifica en qué gastó ese
-- fondo (ver rendiciones.solicitud_fondo_id más abajo).
create table if not exists public.solicitudes_fondos (
  id uuid primary key default gen_random_uuid(),
  -- Correlativo propio de las solicitudes (independiente del folio de
  -- rendiciones). En la app se muestra como "S-{folio}" para no
  -- confundirlo con el N° de una rendición.
  folio bigint generated by default as identity,
  created_at timestamptz not null default now(),
  empleado_id uuid not null references auth.users(id),
  empleado_nombre text not null,
  rut_empleado text,
  empresa text not null,
  centro_costo text,
  monto_solicitado numeric(12,2) not null,
  motivo text not null,
  fecha_necesaria date,
  estado text not null default 'Pendiente' check (estado in ('Pendiente','Aprobado','Rechazado')),
  aprobador_id uuid references auth.users(id),
  aprobador_nombre text,
  fecha_aprobacion timestamptz,
  motivo_rechazo text
);

alter table public.solicitudes_fondos enable row level security;

drop policy if exists "solicitudes_fondos_select" on public.solicitudes_fondos;
drop policy if exists "solicitudes_fondos_insert_own" on public.solicitudes_fondos;
drop policy if exists "solicitudes_fondos_update_approver" on public.solicitudes_fondos;

-- mismo criterio que rendiciones: el empleado ve/crea las suyas, aprobador/admin ve y actualiza todas
create policy "solicitudes_fondos_select" on public.solicitudes_fondos
  for select using (
    empleado_id = auth.uid() or public.is_admin_or_aprobador()
  );

create policy "solicitudes_fondos_insert_own" on public.solicitudes_fondos
  for insert with check (empleado_id = auth.uid());

create policy "solicitudes_fondos_update_approver" on public.solicitudes_fondos
  for update using (
    empleado_id = auth.uid() or public.is_admin_or_aprobador()
  );

create index if not exists idx_solicitudes_fondos_empleado on public.solicitudes_fondos(empleado_id);
create index if not exists idx_solicitudes_fondos_estado on public.solicitudes_fondos(estado);

-- Vincula una rendición tipo "FondoPorRendir" con la solicitud que le dio
-- origen, para poder calcular cuánto del fondo entregado ya se rindió y
-- cuánto queda disponible (ver calcularSplitFondo en app.js).
alter table public.rendiciones add column if not exists solicitud_fondo_id uuid references public.solicitudes_fondos(id);
create index if not exists idx_rendiciones_solicitud_fondo on public.rendiciones(solicitud_fondo_id);

-- ============================================================
-- Nota: la verificación de facturas/boletas NO se hace en este
-- proyecto. Se consulta en vivo, de solo lectura, la tabla
-- "movimientos" del proyecto de contabilidad ya existente
-- (ver CONTABILIDAD_URL / CONTABILIDAD_ANON_KEY en config.js).
-- Este script no toca ese proyecto para nada.
-- ============================================================

-- ============================================================
-- Seguridad: cierra huecos de RLS (ver migracion_seguridad_rls.sql)
-- ============================================================
-- Problema real: las policies de arriba permiten a CUALQUIER usuario
-- autenticado hacer un UPDATE directo vía la API REST de Supabase (sin
-- pasar por la app) y (1) cambiar su propio "rol" a admin, o (2)
-- auto-aprobar su propia rendición/ítem/solicitud de fondos sin que
-- ningún aprobador la revise. Estos triggers cierran ambos huecos del
-- lado del servidor -- la UI no mostrar el botón no alcanza, RLS/triggers
-- son el único gate real. De paso evitan la doble-aprobación por
-- condición de carrera y agregan el registro de auditoría que faltaba
-- para la aprobación/rechazo por ítem.

create or replace function public.proteger_rol_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    if new.rol is distinct from 'empleado' and not public.is_admin() then
      new.rol := 'empleado';
    end if;
  elsif tg_op = 'UPDATE' then
    if new.rol is distinct from old.rol and not public.is_admin() then
      new.rol := old.rol;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_proteger_rol_profile on public.profiles;
create trigger trg_proteger_rol_profile
  before insert or update on public.profiles
  for each row execute function public.proteger_rol_profile();

create or replace function public.proteger_aprobacion_rendicion()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.estado is distinct from old.estado
      or new.aprobador_id is distinct from old.aprobador_id
      or new.aprobador_nombre is distinct from old.aprobador_nombre
      or new.fecha_aprobacion is distinct from old.fecha_aprobacion
      or new.motivo_rechazo is distinct from old.motivo_rechazo
      or new.numero_comprobante_kame is distinct from old.numero_comprobante_kame)
     and not public.is_admin_or_aprobador() then
    raise exception 'Solo un aprobador o admin puede aprobar/rechazar una rendición.';
  end if;

  if new.estado is distinct from old.estado and old.estado <> 'Pendiente' then
    raise exception 'Esta rendición ya fue procesada (estado actual: %).', old.estado;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_proteger_aprobacion_rendicion on public.rendiciones;
create trigger trg_proteger_aprobacion_rendicion
  before update on public.rendiciones
  for each row execute function public.proteger_aprobacion_rendicion();

-- OJO: a diferencia de rendiciones/solicitudes, acá NO se bloquea volver a
-- cambiar el estado una vez que salió de "Pendiente": mientras la rendición
-- completa siga Pendiente, el aprobador puede aprobar/rechazar cada ítem
-- las veces que quiera antes de pulsar "Finalizar aprobación" (comportamiento
-- ya existente de la app). Lo único que se cierra acá es que solo un
-- aprobador/admin puede tocar estos campos.
create or replace function public.proteger_aprobacion_item()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.estado is distinct from old.estado
      or new.motivo_rechazo is distinct from old.motivo_rechazo
      or new.existe_en_contabilidad is distinct from old.existe_en_contabilidad
      or new.comprobante_contable_encontrado is distinct from old.comprobante_contable_encontrado)
     and not public.is_admin_or_aprobador() then
    raise exception 'Solo un aprobador o admin puede aprobar/rechazar o verificar un ítem.';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_proteger_aprobacion_item on public.rendicion_items;
create trigger trg_proteger_aprobacion_item
  before update on public.rendicion_items
  for each row execute function public.proteger_aprobacion_item();

create or replace function public.auditar_cambio_estado_item()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.estado is distinct from old.estado then
    insert into public.rendicion_items_historial
      (item_id, rendicion_id, usuario_id, usuario_nombre, campo, valor_anterior, valor_nuevo)
    select new.id, new.rendicion_id, auth.uid(),
           (select nombre from public.profiles where id = auth.uid()),
           'estado', old.estado, new.estado;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_auditar_cambio_estado_item on public.rendicion_items;
create trigger trg_auditar_cambio_estado_item
  after update on public.rendicion_items
  for each row execute function public.auditar_cambio_estado_item();

create or replace function public.proteger_aprobacion_solicitud()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if (new.estado is distinct from old.estado
      or new.aprobador_id is distinct from old.aprobador_id
      or new.aprobador_nombre is distinct from old.aprobador_nombre
      or new.fecha_aprobacion is distinct from old.fecha_aprobacion
      or new.motivo_rechazo is distinct from old.motivo_rechazo)
     and not public.is_admin_or_aprobador() then
    raise exception 'Solo un aprobador o admin puede aprobar/rechazar una solicitud de fondos.';
  end if;

  if new.estado is distinct from old.estado and old.estado <> 'Pendiente' then
    raise exception 'Esta solicitud ya fue procesada (estado actual: %).', old.estado;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_proteger_aprobacion_solicitud on public.solicitudes_fondos;
create trigger trg_proteger_aprobacion_solicitud
  before update on public.solicitudes_fondos
  for each row execute function public.proteger_aprobacion_solicitud();

-- Restricción de "cuentas permitidas" repetida del lado del servidor
-- (hoy solo filtraba el <select> en el navegador). Solo aplica a un
-- ítem "Gasto directo" (SinDocumento) tocado por su propio dueño; un
-- aprobador/admin corrigiendo la cuenta al verificar en contabilidad
-- no está sujeto a esta restricción.
create or replace function public.validar_cuenta_permitida()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  es_propio boolean;
  tiene_restricciones boolean;
  cuenta_permitida boolean;
begin
  if new.tipo_item <> 'SinDocumento' or new.cuenta_contable is null or new.cuenta_contable = '' then
    return new;
  end if;

  select exists (
    select 1 from public.rendiciones r
    where r.id = new.rendicion_id and r.empleado_id = auth.uid()
  ) into es_propio;

  if not es_propio then
    return new;
  end if;

  select exists (
    select 1 from public.perfil_cuentas where profile_id = auth.uid()
  ) into tiene_restricciones;

  if not tiene_restricciones then
    return new;
  end if;

  select exists (
    select 1 from public.perfil_cuentas
    where profile_id = auth.uid() and cuenta_cod = new.cuenta_contable
  ) into cuenta_permitida;

  if not cuenta_permitida then
    raise exception 'La cuenta % no está habilitada para tu perfil.', new.cuenta_contable;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validar_cuenta_permitida on public.rendicion_items;
create trigger trg_validar_cuenta_permitida
  before insert or update on public.rendicion_items
  for each row execute function public.validar_cuenta_permitida();

alter table public.rendicion_items drop constraint if exists rendicion_items_monto_positivo;
alter table public.rendicion_items add constraint rendicion_items_monto_positivo check (monto > 0);

alter table public.rendiciones drop constraint if exists rendiciones_monto_total_no_negativo;
alter table public.rendiciones add constraint rendiciones_monto_total_no_negativo check (monto_total >= 0);

alter table public.solicitudes_fondos drop constraint if exists solicitudes_fondos_monto_positivo;
alter table public.solicitudes_fondos add constraint solicitudes_fondos_monto_positivo check (monto_solicitado > 0);

-- ============================================================
-- Plantillas de perfil + desactivar usuario (ver migracion_plantillas_perfil.sql)
-- ============================================================
-- ------------------------------------------------------------
-- Plantillas de perfil (ej. "Analista", "Comercial RFA"): agrupan un set de
-- cuentas contables permitidas que se le puede asignar a varias personas a
-- la vez, en vez de configurar cuenta por cuenta a cada una desde cero.
-- Las cuentas permitidas de una persona son la UNIÓN de las de su plantilla
-- (si tiene una) + sus cuentas individuales en perfil_cuentas -- una no
-- reemplaza a la otra, se suman.
-- ------------------------------------------------------------
create table if not exists public.perfil_plantillas (
  id uuid primary key default gen_random_uuid(),
  nombre text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.plantilla_cuentas (
  id uuid primary key default gen_random_uuid(),
  plantilla_id uuid not null references public.perfil_plantillas(id) on delete cascade,
  cuenta_cod text not null,
  cuenta_nombre text,
  unique (plantilla_id, cuenta_cod)
);

create index if not exists idx_plantilla_cuentas_plantilla on public.plantilla_cuentas(plantilla_id);

-- "on delete set null": si se borra la plantilla, la gente que la tenía
-- asignada no queda sin perfil -- simplemente vuelve a depender solo de sus
-- cuentas individuales (si tenía).
alter table public.profiles add column if not exists plantilla_id uuid references public.perfil_plantillas(id) on delete set null;
create index if not exists idx_profiles_plantilla on public.profiles(plantilla_id);

-- Desactivar en vez de eliminar: un borrado real de auth.users no se puede
-- hacer desde el frontend (requiere la Admin API con la clave secreta, que
-- nunca debe quedar expuesta en el navegador) y además rompería el
-- historial contable (rendiciones.empleado_id referencia a auth.users). Una
-- persona desactivada no puede volver a entrar (ver onLoggedIn en app.js),
-- pero todo lo que ya rindió/aprobó queda intacto.
alter table public.profiles add column if not exists activo boolean not null default true;

-- ------------------------------------------------------------
-- RLS: plantillas
-- ------------------------------------------------------------
alter table public.perfil_plantillas enable row level security;
alter table public.plantilla_cuentas enable row level security;

drop policy if exists "plantillas_select" on public.perfil_plantillas;
drop policy if exists "plantillas_admin_write" on public.perfil_plantillas;
drop policy if exists "plantilla_cuentas_select" on public.plantilla_cuentas;
drop policy if exists "plantilla_cuentas_admin_write" on public.plantilla_cuentas;

-- Cualquier autenticado puede leer las plantillas -- las necesita para ver
-- el nombre de la propia y para que cargarCuentasPermitidas() en app.js
-- pueda armar el set de cuentas que le corresponden. Solo el admin las
-- crea/edita/borra.
create policy "plantillas_select" on public.perfil_plantillas
  for select using (auth.uid() is not null);

create policy "plantillas_admin_write" on public.perfil_plantillas
  for all using (public.is_admin()) with check (public.is_admin());

create policy "plantilla_cuentas_select" on public.plantilla_cuentas
  for select using (auth.uid() is not null);

create policy "plantilla_cuentas_admin_write" on public.plantilla_cuentas
  for all using (public.is_admin()) with check (public.is_admin());

-- ------------------------------------------------------------
-- validar_cuenta_permitida: además de perfil_cuentas (individual), ahora
-- también cuentan las cuentas de la plantilla asignada al perfil --
-- "plantilla + extras", no "una u otra".
-- ------------------------------------------------------------
create or replace function public.validar_cuenta_permitida()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  es_propio boolean;
  tiene_restricciones boolean;
  cuenta_permitida boolean;
begin
  if new.tipo_item <> 'SinDocumento' or new.cuenta_contable is null or new.cuenta_contable = '' then
    return new;
  end if;

  select exists (
    select 1 from public.rendiciones r
    where r.id = new.rendicion_id and r.empleado_id = auth.uid()
  ) into es_propio;

  if not es_propio then
    return new;
  end if;

  select exists (
    select 1 from public.perfil_cuentas where profile_id = auth.uid()
    union all
    select 1 from public.profiles p
      join public.plantilla_cuentas pc on pc.plantilla_id = p.plantilla_id
    where p.id = auth.uid()
  ) into tiene_restricciones;

  if not tiene_restricciones then
    return new;
  end if;

  select exists (
    select 1 from public.perfil_cuentas
    where profile_id = auth.uid() and cuenta_cod = new.cuenta_contable
    union all
    select 1 from public.profiles p
      join public.plantilla_cuentas pc on pc.plantilla_id = p.plantilla_id
    where p.id = auth.uid() and pc.cuenta_cod = new.cuenta_contable
  ) into cuenta_permitida;

  if not cuenta_permitida then
    raise exception 'La cuenta % no está habilitada para tu perfil.', new.cuenta_contable;
  end if;

  return new;
end;
$$;

-- ------------------------------------------------------------
-- Protege plantilla_id/activo igual que ya se protegía "rol" (ver
-- proteger_rol_profile en migracion_seguridad_rls.sql): sin esto, cualquier
-- usuario autenticado podría auto-asignarse una plantilla con más cuentas o
-- reactivarse a sí mismo con un UPDATE directo a la API REST, sin pasar por
-- la UI. Solo un admin puede cambiar estos dos campos.
-- ------------------------------------------------------------
create or replace function public.proteger_plantilla_activo_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    -- Mismo criterio que proteger_rol_profile con "rol": un signup propio
    -- (profiles_upsert_own solo exige id = auth.uid(), no restringe estas
    -- columnas) no puede nacer con una plantilla auto-asignada ni
    -- desactivado -- sin este branch, alguien podía registrarse eligiendo
    -- de antemano la plantilla con más cuentas permitidas.
    if not public.is_admin() then
      new.plantilla_id := null;
      new.activo := true;
    end if;
  elsif tg_op = 'UPDATE' then
    if (new.plantilla_id is distinct from old.plantilla_id or new.activo is distinct from old.activo)
       and not public.is_admin() then
      new.plantilla_id := old.plantilla_id;
      new.activo := old.activo;
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_proteger_plantilla_activo_profile on public.profiles;
create trigger trg_proteger_plantilla_activo_profile
  before insert or update on public.profiles
  for each row execute function public.proteger_plantilla_activo_profile();

-- ------------------------------------------------------------
-- Policy de DELETE en rendiciones (no relacionada a plantillas, pero se
-- agrega en esta misma migración porque la necesita el fix de "rendición
-- fantasma" en app.js): hoy rendiciones tiene RLS activado pero SIN
-- ninguna policy de DELETE, así que cualquier intento de borrar (incluido
-- el que hace submitRendicion() cuando todos los ítems de una rendición
-- recién creada fallan al guardarse) queda bloqueado en silencio -- el
-- DELETE "funciona" (error: null) pero afecta 0 filas, dejando la
-- rendición fantasma igual. Esta policy es deliberadamente angosta: solo
-- deja borrar una rendición PROPIA, Pendiente, y que todavía no tenga
-- ningún ítem guardado -- no habilita "eliminar rendición" como función
-- general para el usuario.
-- ------------------------------------------------------------
drop policy if exists "rendiciones_delete_propia_vacia" on public.rendiciones;
create policy "rendiciones_delete_propia_vacia" on public.rendiciones
  for delete using (
    empleado_id = auth.uid()
    and estado = 'Pendiente'
    and not exists (select 1 from public.rendicion_items ri where ri.rendicion_id = rendiciones.id)
  );

-- ------------------------------------------------------------
-- "Desactivar usuario" hasta acá solo bloqueaba el login DESDE LA APP
-- (onLoggedIn en app.js) -- nada en las policies revisaba "activo", así
-- que una persona desactivada que igual conservara su sesión/contraseña
-- podía seguir usando la API REST de Supabase directo, sin pasar por la
-- app, con los mismos permisos de siempre. Si era aprobador/admin,
-- mantenía ESE poder indefinidamente incluso desactivada. Esto lo cierra
-- del lado del servidor, que es el único lado que realmente cuenta.
-- ------------------------------------------------------------
create or replace function public.is_admin_or_aprobador()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.rol in ('aprobador','admin') and p.activo
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.rol = 'admin' and p.activo
  );
$$;

-- Además, para que una persona desactivada tampoco pueda seguir creando
-- rendiciones/ítems/solicitudes nuevas a su propio nombre vía API directa
-- (ver una desactivada su propio historial viejo no es un problema de
-- seguridad, así que las policies de SELECT no se tocan -- solo las de
-- INSERT de cosas nuevas).
create or replace function public.is_activo()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select p.activo from public.profiles p where p.id = auth.uid()), true);
$$;

drop policy if exists "rendiciones_insert_own" on public.rendiciones;
create policy "rendiciones_insert_own" on public.rendiciones
  for insert with check (empleado_id = auth.uid() and public.is_activo());

drop policy if exists "items_insert_own" on public.rendicion_items;
create policy "items_insert_own" on public.rendicion_items
  for insert with check (
    public.is_activo()
    and exists (
      select 1 from public.rendiciones r
      where r.id = rendicion_items.rendicion_id and r.empleado_id = auth.uid()
    )
  );

drop policy if exists "solicitudes_fondos_insert_own" on public.solicitudes_fondos;
create policy "solicitudes_fondos_insert_own" on public.solicitudes_fondos
  for insert with check (empleado_id = auth.uid() and public.is_activo());
